### ISSUE TITLE
Does not work with 6.4.2...

### ISSUE THREAD

**Issue by smcpoland** [bonitasoft/bonita-examples#1]
Also on Community Answers @ http://community.bonitasoft.com/answers/maven-example-does-not-work-642
### Hi there,

trying the Maven example with 6.4.1 works fine but when changing only the bonita.home to point to a 6.4.2 system I get an error. The code does not change at all:

Seems to fail on

_getPlatformAPI(session).createAndInitializePlatform();_

CODE:

``` java
private static void createPlatform() throws BonitaException {
// login as platform administrator
PlatformSession session = doPlatformLogin(PLATFORM_ADMIN,
PLATFORM_PASSWORD);
System.out.println("Got a Session: "+session.toString());
try {
System.out.println("Creating and initializing the platform ...");
// create and initialize the platform
getPlatformAPI(session).createAndInitializePlatform();
System.out.println("Platform created and initialized!");

System.out.println("Starting node ...");
// start the node (make scheduler service to start)
getPlatformAPI(session).startNode();
System.out.println("Node started!");
} finally {
// logout
doPlatformLogout(session);
}
}
```

```
Feb 11, 2015 2:44:09 PM org.hibernate.type.TypeFactory$TypeScopeImpl injectSessionFactory
WARN: HHH000233: Scoping types to session factory org.hibernate.internal.SessionFactoryImpl@4fb77a00 after already scoped org.hibernate.internal.SessionFactoryImpl@16aabee3

Got a Session: SessionImpl [id=2889886930029740249, creationDate=Wed Feb 11 14:44:20 AST 2015, duration=3600000, userName=platformAdmin, userId=0, technicalUser=false]
Creating and initializing the platform ...

SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Feb 11, 2015 2:44:21 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
WARN: SQL Error: 42102, SQLState: 42S02
Feb 11, 2015 2:44:21 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
ERROR: Table "PLATFORM" not found; SQL statement:
select splatformi0_.id as id1_33_, splatformi0_.created as created2_33_, splatformi0_.createdBy as createdB3_33_, splatformi0_.initialVersion as initialV4_33_, splatformi0_.previousVersion as previous5_33_, splatformi0_.version as version6_33_ from platform splatformi0_ limit ? [42102-170]
Feb 11, 2015 2:44:22 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.bonitasoft.engine.service.impl.AbsoluteFileSystemXmlApplicationContext@1720d4d7: startup date [Wed Feb 11 14:44:22 AST 2015]; parent: org.bonitasoft.engine.service.impl.AbsoluteFileSystemXmlApplicationContext@3fc52f9e
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-actor-mapping-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-archive-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-authentication-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-category-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-command-api-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-connector-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-connector-service-api-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-data-instance-api-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-data-transient.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-dependency-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-document-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-events-api-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-expression-api-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-expression-resolver.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-external-identity-mapping-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-identity-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-log-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-log-technical-slf4j.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-login.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-permission.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-process-comment-api-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-process-definition-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-process-instance-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-profile-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-supervisor-mapping-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-tenant-configuration.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-theme-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-time-tracker.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-user-filter-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-work-factory.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bonita-work-impl.xml]
Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg-bos-operation-api-impl.xml]

Feb 11, 2015 2:44:22 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from file [E:\Bonita\Bonita 642\BonitaBPMCommunity-6.4.2-Tomcat-7.0.55\bonita\server\tenants\1\conf\services\cfg.xml]
Feb 11, 2015 2:44:23 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@9fa27e9: defining beans [actorMappingService,archiveService,authenticationService,categoryService,commandService,defaultCommandProvider,canStartProcessDefinition,isInvolvedInHumanTask,isUserProcessSupervisor,createSupervisor,getSupervisor,deleteSupervisor,searchProcessSupervisors,importProfiles,executeActionsAndTerminate,isAllowedToStartProcess,isAllowedToSeeOverviewForm,isAllowedToSeeInstanciationForm,searchAssignedTasksSupervisedBy,searchArchivedTasksSupervisedBy,getUpdatedVariableValuesForProcessDefinition,getUpdatedVariableValuesForActivityInstance,getUpdatedVariableValuesForProcessInstance,searchProcessDefinitionsSupervisedBy,searchSCommentSupervisedBy,isAllowedToStartProcesses,addEntityMemberCommand,removeEntityMemberCommand,searchEntityMembersCommand,searchEntityMembersForUserCommand,deleteEntityMembersCommand,searchWaitingEventsCommand,advancedStartProcessCommand,connectorExecutor,connectorServiceSub,connectorService,connectorInstanceService,dataInstanceService,dataExpressionExecutorStrategy,transientDataService,transientDataExpressionExecutorStrategy,dependencyService,documentService,documentURLProvider,eventService,expressionService,expressionExecutorStrategyProvider,constantExpressionExecutorStrategy,groovyScriptExpressionExecutorStrategy,inputExpressionExecutorStrategy,patternExpressionExecutorStrategy,xPathReadExpressionExecutorStrategy,engineConstantExpressionExecutorStrategy,listExpressionExecutorStrategy,equalityComparator,inequalityComparator,binaryComparatorMapper,binaryComparatorExecutor,logicalComplementExecutor,conditionExpressionExecutorStrategy,javaMethodCallExpressionExecutorStrategy,expressionResolverService,externalIdentityMappingService,identityService,queriableLoggerStrategy,syncQueriableLoggerService,tenantTechnicalLoggerService,loginService,permissionService,commentService,processDefinitionManager,activityInstanceService,processInstanceService,tokenService,gatewayInstanceService,transitionService,eventInstanceService,profileService,supervisorMappingService,tenantConfiguration,timerEventTriggerJobListener,themeService,timeTracker,userFilterService,userFilterServiceSub,bonitaExecutorServiceFactory,workService,operationService,operationExecutorStrategyProvider,leftOperandHandlerProvider,assignmentOperationExecutorStrategy,dataLeftOperandHandler,transientDataLeftOperandHandler,externalDataLeftOperandHandler,javaMethodOperationExecutorStrategy,xpathUpdateQueryOperationExecutorStrategy,documentLeftOperandHandler,documentListLeftOperandHandler,queriableLogSessionProvider,tenantRecorderSync,searchEntitiesDescriptor,flowNodeExecutor,containerRegistry,bpmInstancesCreator,flowNodeStateManager,eventsHandler,transitionConditionEvaluator,defaultTransitionGetter,implicitGatewayTransitionEvaluator,inclusiveGatewayTransitionEvaluationStrategy,exclusiveGatewayTransitionEvaluationStrategy,inclusiveTransitionEvaluator,exclusiveTransitionEvaluator,parallelGatewayTransitionEvaluator,transitionEvaluator,processExecutor,transactionalProcessInstanceInterruptor,documentReferenceExpressionExecutorStrategy,documentListReferenceExpressionExecutorStrategy,dependencyResolver]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@609919c9

Feb 11, 2015 2:44:23 PM org.springframework.beans.factory.support.DefaultSingletonBeanRegistry destroySingletons
INFO: Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@9fa27e9: defining beans [actorMappingService,archiveService,authenticationService,categoryService,commandService,defaultCommandProvider,canStartProcessDefinition,isInvolvedInHumanTask,isUserProcessSupervisor,createSupervisor,getSupervisor,deleteSupervisor,searchProcessSupervisors,importProfiles,executeActionsAndTerminate,isAllowedToStartProcess,isAllowedToSeeOverviewForm,isAllowedToSeeInstanciationForm,searchAssignedTasksSupervisedBy,searchArchivedTasksSupervisedBy,getUpdatedVariableValuesForProcessDefinition,getUpdatedVariableValuesForActivityInstance,getUpdatedVariableValuesForProcessInstance,searchProcessDefinitionsSupervisedBy,searchSCommentSupervisedBy,isAllowedToStartProcesses,addEntityMemberCommand,removeEntityMemberCommand,searchEntityMembersCommand,searchEntityMembersForUserCommand,deleteEntityMembersCommand,searchWaitingEventsCommand,advancedStartProcessCommand,connectorExecutor,connectorServiceSub,connectorService,connectorInstanceService,dataInstanceService,dataExpressionExecutorStrategy,transientDataService,transientDataExpressionExecutorStrategy,dependencyService,documentService,documentURLProvider,eventService,expressionService,expressionExecutorStrategyProvider,constantExpressionExecutorStrategy,groovyScriptExpressionExecutorStrategy,inputExpressionExecutorStrategy,patternExpressionExecutorStrategy,xPathReadExpressionExecutorStrategy,engineConstantExpressionExecutorStrategy,listExpressionExecutorStrategy,equalityComparator,inequalityComparator,binaryComparatorMapper,binaryComparatorExecutor,logicalComplementExecutor,conditionExpressionExecutorStrategy,javaMethodCallExpressionExecutorStrategy,expressionResolverService,externalIdentityMappingService,identityService,queriableLoggerStrategy,syncQueriableLoggerService,tenantTechnicalLoggerService,loginService,permissionService,commentService,processDefinitionManager,activityInstanceService,processInstanceService,tokenService,gatewayInstanceService,transitionService,eventInstanceService,profileService,supervisorMappingService,tenantConfiguration,timerEventTriggerJobListener,themeService,timeTracker,userFilterService,userFilterServiceSub,bonitaExecutorServiceFactory,workService,operationService,operationExecutorStrategyProvider,leftOperandHandlerProvider,assignmentOperationExecutorStrategy,dataLeftOperandHandler,transientDataLeftOperandHandler,externalDataLeftOperandHandler,javaMethodOperationExecutorStrategy,xpathUpdateQueryOperationExecutorStrategy,documentLeftOperandHandler,documentListLeftOperandHandler,queriableLogSessionProvider,tenantRecorderSync,searchEntitiesDescriptor,flowNodeExecutor,containerRegistry,bpmInstancesCreator,flowNodeStateManager,eventsHandler,transitionConditionEvaluator,defaultTransitionGetter,implicitGatewayTransitionEvaluator,inclusiveGatewayTransitionEvaluationStrategy,exclusiveGatewayTransitionEvaluationStrategy,inclusiveTransitionEvaluator,exclusiveTransitionEvaluator,parallelGatewayTransitionEvaluator,transitionEvaluator,processExecutor,transactionalProcessInstanceInterruptor,documentReferenceExpressionExecutorStrategy,documentListReferenceExpressionExecutorStrategy,dependencyResolver]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@609919c9

Node not started. Method 'org.bonitasoft.engine.api.LoginAPI.login' cannot be called until node has been started (PlatformAPI.startNode())
Exception in thread "main" org.bonitasoft.engine.platform.NodeNotStartedException: The current node has not been started yet. Method PlatformAPI.startNode() must be called previously.

at org.bonitasoft.engine.api.impl.ServerAPIImpl.checkMethodAccessibility(ServerAPIImpl.java:286)
at org.bonitasoft.engine.api.impl.ServerAPIImpl.invokeAPIOutsideTransaction(ServerAPIImpl.java:279)
at org.bonitasoft.engine.api.impl.ServerAPIImpl.invokeAPI(ServerAPIImpl.java:272)
at org.bonitasoft.engine.api.impl.ServerAPIImpl.invokeMethod(ServerAPIImpl.java:128)
at org.bonitasoft.engine.api.impl.ClientInterceptor.invoke(ClientInterceptor.java:88)
at com.sun.proxy.$Proxy10.login(Unknown Source)
at org.bonitasoft.example.App.doTenantLogin(App.java:1118)
at org.bonitasoft.example.App.deleteUser(App.java:1052)
at org.bonitasoft.example.App.main(App.java:180)

```

**Comment by educhastenier** [comment]
Question anwsered on http://community.bonitasoft.com/answers/maven-example-does-not-work-642
